name: matrix-commander-gael
base: core22
version: "6.0.1-20230301"
summary: Simple but convenient CLI-based Matrix client app
description: |
  This program is a simple but convenient app to send and receive Matrix messages from the CLI in various different ways.
  Use cases for this program could be
  - a bot or part of a bot,
  - to send alerts,
  - combine it with cron to publish periodic data,
  - send yourself daily/weekly reminders via a cron job
  - send yourself a daily song from your music collection
  - a trivial way to fire off some instant messages from the command line
  - to automate sending via programs and scripts
  - a "blogger" who frequently sends messages and images to the same room(s) could use it
  - a person could write a diary or run a gratitutde journal by sending messages to her/his own room
  - as educational material that showcases the use of the matrix-nio SDK
grade: stable
confinement: strict

architectures:
  - build-on: arm64
  - build-on: amd64

license: "GPL-3.0"

apps:
  matrix-commander:
    command: matrix_commander.py
    completer: matrix-commander.bash
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3.10:$SNAP/usr/lib/python3.10/lib-dynload:$SNAP/lib/python3.10/site-packages
      MAGIC: $SNAP/usr/share/file/magic.mgc
    plugs:
      - home
      - network
      - network-bind

parts:
  app:
    plugin: python
    source: https://github.com/8go/matrix-commander.git
    source-type: git
    source-tag: "v6.0.1"
    python-requirements:
      - requirements.txt
        #    filesets:
        #      files2keep: [etc, bin, lib, lib64, share, usr, matrix_commander.py, matrix-commander.bash]
        #      files2delete: [-usr/share/man, -usr/share/bug, -usr/share/doc, -usr/share/lintian]

    override-build: |
      apt-get install build-essential libpython3-dev libpython3.10-stdlib libdbus-1-dev libglib2.0-dev libmagic-dev libolm-dev pkg-config python3-pip

      snapcraftctl build

      cp $SNAPCRAFT_PART_BUILD/matrix_commander/matrix_commander.py $SNAPCRAFT_PART_INSTALL
      cp $SNAPCRAFT_PART_BUILD/auto-completion/bash/matrix-commander.bash $SNAPCRAFT_PART_INSTALL

      rm -rf $SNAPCRAFT_PART_INSTALL/lib/python3.10/site-packages/argparse*
    stage:
      - etc
      - bin
      - lib
      - lib64
        #      - share
      - usr
      - matrix_commander.py
      - matrix-commander.bash
      - -usr/share/man
      - -usr/share/bug
      - -usr/share/doc
      - -usr/share/lintian
        #      - $files2keep
        #      - $files2delete
    stage-packages:
      - libolm3
      - python3-venv
      - libpython3.10-stdlib
      - libmagic1
      - libmagic-mgc
