name: matrix-commander-gael
base: core24
version: "7.6.2"
summary: Simple but convenient CLI-based Matrix client app
description: |
  This program is a simple but convenient app to send and receive Matrix messages from the CLI in various different ways.
  Use cases for this program could be
  - a bot or part of a bot,
  - to send alerts,
  - combine it with cron to publish periodic data,
  - send yourself daily/weekly reminders via a cron job
  - send yourself a daily song from your music collection
  - a trivial way to fire off some instant messages from the command line
  - to automate sending via programs and scripts
  - a "blogger" who frequently sends messages and images to the same room(s) could use it
  - a person could write a diary or run a gratitutde journal by sending messages to her/his own room
  - as educational material that showcases the use of the matrix-nio SDK
grade: stable
confinement: strict

platforms:
  arm64:
    build-on: arm64
    build-for: arm64
  amd64:
    build-on: amd64
    build-for: amd64

license: "GPL-3.0"

apps:
  matrix-commander:
    command: matrix_commander.py
    completer: matrix-commander.bash
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3.12:$SNAP/usr/lib/python3.12/lib-dynload:$SNAP/lib/python3.12/site-packages
      MAGIC: $SNAP/usr/share/file/magic.mgc
    plugs:
      - home
      - network
      - network-bind

parts:
  app:
    plugin: python
    source: https://github.com/8go/matrix-commander.git
    source-type: git
    source-tag: "v7.6.2"
    python-requirements:
      - requirements.txt

    override-build: |
      apt-get install build-essential libpython3-dev libpython3.12-stdlib libdbus-1-dev libglib2.0-dev libmagic-dev libolm-dev pkg-config python3-pip

      craftctl default

      cp $SNAPCRAFT_PART_BUILD/matrix_commander/matrix_commander.py $SNAPCRAFT_PART_INSTALL
      cp $SNAPCRAFT_PART_BUILD/auto-completion/bash/matrix-commander.bash $SNAPCRAFT_PART_INSTALL
      sed -i 's/matrix-commander.py/matrix-commander-gael.matrix-commander.py/g' $SNAPCRAFT_PART_INSTALL/matrix-commander.bash

      rm -rf $SNAPCRAFT_PART_INSTALL/lib/python3.12/site-packages/argparse*
    stage:
      - bin
      - lib
      - lib64
      - usr
      - matrix_commander.py
      - matrix-commander.bash
      - -usr/share/man
      - -usr/share/bug
      - -usr/share/doc
      - -usr/share/lintian
    stage-packages:
      - libolm3
      - python3-venv
      - libpython3.12-stdlib
      - libmagic1
      - libmagic-mgc
